name: baseball-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - pip>=23.0.0
  - duckdb>=0.9.0
  - pip:
    - pybaseball>=2.2.0
